---
title: "casting"
---

-   If bottom is patterned sand and grass, cast over the sand spots and reel across them
-   Watch how tide interacts with mangroves, little pockets become available
-   Leave a 2-3 feet of line out when casting to skip it under mangroves
-   cast beyond dock, reel through (wading)
-   use finger to 'feather the line' when casting - slow how it comes out
-   Vary retrieve at beginning of session until you can find what is working. Use that retrieve until it stops working for some time and then test again.


[Casting mastery course by Saltstrong](https://www.saltstrong.com/casting/casting-mastery/welcome/)

### Dart casting

-   Forward and back over your head
-   Timing will be different based on power and action of rod
-   start out with rod towards target
-   Backswing : lift up both hands, just past straight up
-   Feel maximum rod bend then snap it forward
-   Minimize movement, head still

### Skip casting

-   Lure around 6-10 inches from rod tip
-   Same action as overhand but to the side
    -   90 degrees to target
-   keep rod low and parallel to water
-   as much speed as possible with control
-   Control (reduce) distance by 'feathering' the line with finger or flipping bail for hard stop

### Accuracy casting

-   Cast from the side when you want to avoid spooking fish
    -   Less likely for fish to see cast
-   Cast to a target rather than just around the fish (to gauge accuracy)
-   Practice accuracy from non-favoured side

### Sight casting

-   Cast beyond fish
-   Small fish
-   Retrieve in natural way with current
-   Make sure line does not go directly over fish (target or others) when shallow

### Fixing line twists

-   let line out 75-100m behind the boat
-   Let sit for a little while
-   Reel in with tension
