---
title: "Docks and canals"
---

## [Canal fishing](https://www.saltstrong.com/canalfishingmastery/introduction/welcome/)

Ideal for fishing in the wind and bad weather

### Locating fish

-   Narrower than 30m
-   Semi isolated, but not dead-end
-   6-10ft deep with a steep drop off
-   Focus on structure that sticks out into the canals
-   Canals with some, but not a lot of current are best
-   Canals that are dead end but have a little outlet can be great
-   Short docks that don't stick far into canal are the best
-   Mangroves and docks are a great combination
-   Docks with lots of barnacle growth, falling apart, submerged structure are good
-   look for something different e.g. area with a lot of concrete then mangrove bush

### Gear

-   Live bait
    -   1/4oz split shot + 2ft 20lb leader + Number 2 hook (gamaktsu octopus hook)
    -   rig by pinching tail off and putting hook through where tail was

### technique

-   Cast directly towards, rather than along, the shortline - will reduce snags / allow you to pull fish out
-   Bait needs to be on the bottom near edge, don't tighten line before its on the bottom
    -   Keep rod tip high and feed line out before flipping bail
    -   Don't drag away from structure
-   Put bait under dock, and give it 1 minute then jiggle
-   12x casts to each dock

### Bridge fishing

-   golden brim terroreyez (texas croaker with yellow jighead (small weight head)), bounce the bottom around a bridge (when cold fish are deeper)

## Fishing docks

[Dock fishing mastery course by Saltstrong](https://www.saltstrong.com/fishing-tip/docks-fishing-mini-course/)

Fishing docks with 30lb test because of pilings etc

### Positioning

-   Downcurrent of targeted dock, perpendicular

### Casting

-   Cast at an angle (30-45 degrees) beyond dock and let lure sink to bottom
-   Let current take it towards first piling (relative to current) while bouncing lure
-   Then move to other pilings using skip cast approach
-   Fish hang around pilings so be within 1-2ft from pilings to maximize bites
-   When you catch one, there' likely more
-   Weedless allows you to skip further under dock

### Tackle

-   20lb braid
-   Medium heavy rod
-   3000 reel
-   Mono 30-40lb better for abrasion
-   baitfish and crustacean imitation lures at two different sizes
-   [powerprawn](https://fishstrong.com/products/power-prawn-usa-original?variant=42285567017134) preferred by Luke @ Saltstrong
-   Increase weight with depth (1/4oz 4-6ft, 1/2oz 6-10ft)
-   If a lot of structure go with weedless weighted hooks
-   Exposed hook jighead if not a lot of structure
  - But there are weedless zman jigheads (worse hookup ratio)
  
### [Fishing inshore structure course by Saltstrong](https://www.saltstrong.com/fishing-tip/fishing-inshore-structure-mini-course/)

-   Strike zone is 1-2ft around structure
-   Most fish will be towards the bottom
-   Keep bail open as bait lands to allow bait to fall straight down and stay close to structure
-   Feed line out with hand to make it drop faster
-   Cast beyond structure
-   If current is strong keep rod tip up so line is out water and no 'belly' is created

### Mangroves

-   Keep line loose after cast so it stays in place
-   Don't reel too much initially (1 turn of reel =~ 1m of line)
-   Cast upcurrent of mangrove points, deep into the shoreline
