---
title: "examples"
---

<https://www.youtube.com/watch?v=UJRSiD4JCQI>

General:

-   Voodoo shrimp beneath mangroves
-   Fish topwater (yo zuri) seawall and docks connecting to shore.
-   Slam shady on trout eye jighead
-   Topwater lure yozuri hydro pencil (yellow / bronze) in school of
mullet being hunter. Near rocks / bridge, early morning. Switched to
bib'd yozuri that looks like finger mullet gray/silver/white

Snook:

-   Yo-zuri topwater yellow/silver
-   Jighead + 4 inch finback shad (paddletail) with procure under
docks, 30lb leader, 4000 reel, 7ft medium fast rod
-   Dead alive swimmer (white) seawall between
-   3inch zman
-   Rapala diving 4inch
-   Finback shad with jighead 4inch brown/light near docks
-   [White jerk shad (large 7in)](https://www.amazon.com/gp/product/B00FPQP99G/ref=as_li_tl?ie=UTF8&tag=fishfish0c-20&camp=1789&creative=9325&linkCode=as2&creativeASIN=B00FPQP99G&linkId=ad38876ff2fc908718b62a4a7d6af29a) on jighead 7ft fast action, 3000 reel, in between/under docks near shore Indian river 15lb braid 40lb leader (30 if calm). Sink lure to bottom and hop.
-   [mullet
rapala](https://www.basspro.com/shop/en/rapala-saltwater-x-rap?irclickid=QrcXeF2M4xyNT0H2N%3ASXpxqkUkDTLtwFnQ3i300&irpid=2363963&irmpname=Fishaholic%20Fishing&irsharedid=&cm_soc=AFF&irgwc=1&hvarAID=impact)
around bridge docks

Yellow Jack:

-   Large white fluke seawall between docks
-   Trolling swimbait texas style across the river (flat 3-4ft)
behind kayak
-   Zoom super fluke
-   [White jerk shad (large 7in)](https://www.amazon.com/gp/product/B00FPQP99G/ref=as_li_tl?ie=UTF8&tag=fishfish0c-20&camp=1789&creative=9325&linkCode=as2&creativeASIN=B00FPQP99G&linkId=ad38876ff2fc908718b62a4a7d6af29a) on jighead 7ft fast action, 3000 reel, in between/under docks near shore Indian river 15lb braid 40lb leader (30 if calm). Sink lure to bottom and hop.
-   seawalls

AM:

-   azuri 110 topwater plug


Bait:

-   To catch live bait take a bucket and cast net, and something to cover
bucket so fish cant jump out. Bring aquasocks to wade

Mangrove snapper:

-   small hook cutbait after chumming water

Redfish:

-   3inch zman




