---
title: "Finding fish"
---

Use wind to your advantage - wind will blow bait into certain areas

after every fish examine the state of the leader

baitfish, structure and current are the ideal combination
Structure: seagrass, potholes, docks, mangroves, oyster beds
wind-blown shorelines can harbour big fish
look for funnels

20-30 minutes per areas (that has at least some signs of life)

### Trip planning
-   Select 3-5 spots to fish
  -   Based on wind / tide patterns
    -   Fight wind on way to spot, rather than way back
  -   choose a reasonable order

### Fish indicators
-   Mud boils - fish getting spooked and moving away - indicate fish are around
-   Birds are a good indicator
  -   Birds e.g. herons are a better indicator than pelicans diving away from structure
-   Baitfish are another indicator

## Finding fish

[Spots mastery course by Saltstrong](https://www.saltstrong.com/spotsmastery/spots-mastery/welcome/)

### Best water temperature

Most important in Summer and Winter, or extreme weather events.

When cold:

-   Looking for warmth 
-   Sun
-   Dark/muddy bottom absorbs energy
-   No waves (shoreline protected from wind)
-   Shallower water

When warm:

-   looking for dissolved oxygen
-   Moving water
-   current (e.g. tidal) or waves
-   Overhanging mangroves/docks create shade
-   Cooler water is deeper
-   Seagrass
-   Each species have different preferences
-   Bing provides a few different angles of satellite images

### Best time to fish

-   +/- 1hr around sunrise and sunset
-   Angle of slope between high-low tide shows current strength - want strongest. Otherwise wind can be a bigger factor.
-   Avoid slack tides (peaks and troughs)