---
title: "lures"
---

The new 5″ Slam Shady Paddletail rigged on a 5/0 Owner TwistLock hook (but the 4/0 would have been better)
Less is more with paddletail

match the kind of bait that you see with the lure

flat scenario for spoon. if all uniform depth/checkerboard bottom with
spoon you can work it fast and cover a lot of area "search bait" if no
baits slow it down with DOA shrimp. spoon is reaction bite.

Topwaters in the morning


### Soft plastic jerkbaits

-   Try to make jighead hook come out in middle of belly
-   Some lure brands like z-man are less dense so require a heavier hook e.g. 1/8oz 4/0 twistlocks
-   1/16oz 3/0 work for more dense plastic lures
-   1-1.5ft length to skip
  -   Keep low
-   Good for sight fishing as doesnt splash

For soft plastic 'sticks' i.e. non-paddletails
-   1 or 2 bounces then pause to let bait sink
-   Reel in slack as it sinks but make sure not to affect action


### Paddletails

Use 

If windy keep rod tip low to limit effect of wind on line/lure action


### [Artificial shrimp](https://www.saltstrong.com/fishing-tip/artificial-shrimp-mini-course-tips-and-tactics-for-rigging-and-retrieving/)

-   Pre-rigged preference is [chasebaits flick prawn](https://amzn.to/3eDDld7), good for clear water
-   Gulp shrimp good for dirty water. Rig with jighead or twistlock depending on whether depth or structure / weedless is being fished.
-   tie lures on with [non-slip loop knot](https://www.saltstrong.com/articles/non-slip-loop-knot/)
-   Shrimp are more abundant in fall / winter
-   Fish them around structure e.g. docks, rocks, grass flats
-   Cast out, let sink to bottom, 2-3 bounces, then pause. Bounces should be sharp in dirty water.
-   Pause for 2-3 seconds generally (depends on activity / weather)
-   Try to avoid slack in the line.
-   Increase retrieve speed for sea trout and snook so that shrimp doesnt sit on bottom.
-   Early in the morning speed up retrieve and slow as it gets hotter
-   Fall and spring seasons allow for a faster retrieve
-   Prerigged shrimp has slow steady reel as it stays towards the top of the water column
-   One tactic is to let shrimp drift in current with little to no weight
-   Pick shrimp with a little bit of flash to it in more dirty water.

### Sightfishing

-   soft plastic jerkbait (e.g. [5inch zman](https://amzn.to/3TpYd6G) rigged weedless with a hook on shank (e.g. twistlock)

redfish: mirrodene xl when windy

can hook DOA shrimp through the tail with the hooking coming out the
back so it moves backwards like a real shrimp

Mark Nichols favourite colour for 4" shrimp is glow with gold glitter.
Blair likes "electric chicken" for shad for redfish and trout, glow +
gold for shrimp version.

If around glass minnows use "clear holographic"

"rootbeer" terroreyes has been good forever

Add "pro-cure" or something similar. This gives added scent to the lure.

Go to: DOA glow shrimp

trout - CAL gold glow 1/8 oz jighead (natural or chartreuse)

flounder - root beer terroreyes

snook - 4inch DOA cal with perly white body red jighead small CAL fiji
chicken 16oz jighead (grey)

DOA penny shrimp matched red-ish water colour

DOA swimming mullet cavity filled with scent liquid - catch big fish
everywhere....

"always works" brown dog terroreyes, esp tarpon

mirrolure topdog early in the day for trout and reds, stop when topwater
bite quits

3/0 twistlock hook is best for soft plastic jerkbaits

snook and seatrout like a more erratic retrieve
