---
title: "positioning"
---

## Positioning & approach

[Positioning & approach mastery course](https://www.saltstrong.com/positioningcourse/module-1-overview-big-idea/top-factors-big-idea/)

-   Current is most important
-   Wind can also affect where to be
-   Look for current ripples around structure to see whether it is a major factor, or wind is more important.
-   Cast the bait and let it follow the natural flow of the current
-   Fish with the wind at your back
-   Look at how wind interacts with environment e.g. natural choke points that will funnel wind (therefore current and fish)
-   best spot wind and current are opposite directions
    -   best to be upwind and down current
-   Position yourself in shallows when tide is incoming. Fish want to get to where the bait are hiding when its very shallow.
-   Have your bait flow with the current i.e. reel in the same direction as the current
-   If current and wind are going in same direction you will have to face and cast into the wind.
-   Cast at 45 degrees into the wind, rather than head on, to increase accuracy and distance
-   Look for the 'odd' things e.g. white spots in grass flats

### Fishing flats / oyster bars

-   The calmer the water the more stealth needed
-   Pick areas where you can cover different depths by casting at different angles
-   Use the wind to push you to be as quiet as possible
-   On the edge of potholes in grass flats
-   Position yourself in an area that can cover multiple depths
-   Fish don't seem to be in deeper holes
-   Cast far over pothole and work lure back

### Fishing mangroves / shorlines

-   Be downcurrent and cast along mangroves shoreline in the upcurrent direction at 45 degree angle (or less)
-   Fan cast starting downcurrent and moving upcurrent
-   Keep in mind where lure is (depth) to understand where fish are
-   Be about half a cast distance from mangroves / shore when casting
-   If weedless lure gets stuck in mangroves just give it light taps and it will fall in
-   Look for structure / formations that stand out

### Fishing docks

-   Outside pilings first, then inside
-   Cast jig through pilings, let it sink, work jig back keeping it near the bottom

### Fishing strong current

-   Let current/wind move you down current (far enough away so fish can't see you)
-   Cast at a 45 degree angle upcurrent and let bait drift with current as you retrieve
    
### Kayak positioning

-   If facing the wind, start by pushing yourself into the wind by paddling, then cast, so you don't drift back too much.
-   Wind is biggest factor in lagoon systems. It can drive the current.
-   Target the edge of the drop in open water
-   Cast parallel to edge
-   Have the wind to your back
-   Minimize hull slap
-   Wear lighter colors that match the sky
-   Try have the sun on your front

### Kayak paddling

-   Paddle should go into water from heel to hip
-   Paddle at higher angle when you need more power / speed against wind and current.
-   Keep elbows low (not above shoulder) when paddling
-   Keep rod in rod holder, facing away from you
