---
title: "seasons"
---

### Autumn

-   Fish are generally on the points
-   4-6 inch baits as baits are getting bigger
  -   Paddletail or jerk shad
-   Adapt lures to size of visible baits
-   Cut mullet works well
-   Baits that are imitating food - mullet
-   Larger topwaters can be a great tactic as fish are looking for mullet
-   Make sure there are baitfish
-   Early morning or late evening when hot
-   If hot slow retrieve
-   Think about transitional areas between summer and winter months   
-   Grassy areas with deep or muddy potholes

### Fall Season Game Plan Cheat Sheet

-   During this time, you don’t need to worry much about the water temperature because it’s safe to assume that the fish will be comfortable in terms of DO2 (dissolved oxygen) levels and body temperature.
-   So this is the time to put the sole focus on finding areas with the most food for them to eat along with enough protection from predators like dolphin.
-   Bull Redfish Alert… this is the season where many big over-slot redfish push inshore, so be ready for encounters with very strong fish… especially if fishing in or near passes/inlets.
-   Lures: The baitfish are generally at their peak in quantity and size, so it’s smart to use larger baitfish imitation lures at this time. Great season for fun topwater strikes!
-   Timing: During the mild temperature months, the best inshore bite is often in the twilight periods within a couple hours before and after the sun rises and sets. But since the water temperature will stay out of either extreme hot or cold, they will often feed throughout the day and into the night as well… especially at good current flow periods.

The best game plan is generally to prioritize the twilight periods overall, and then heavily factor in the tidal movements to determine when the optimal feeding times will be. 

Favorites:

- Best Bite: Twilight hours & max current periods
- Best Tide: I don’t favor incoming or outgoing during this time… just want good current flow.

Game Plan:

- Morning: I try to get out as early as possible and focus on the shallow flats and/or shorelines with lots of life (birds, bait, and any feeding activity)
- Mid-Day: The fish can be both shallow or deep at this time… typically the best bet is to target the zones with the most bait that’s near structure such oyster bars, shoreline points, potholes on grass flats, etc.
- Evening: This is often a great time to target slams up on the flats or along shorelines in the shallows because they’ll often be actively feeding just like they were in the morning.
- Night: The shadow lines of docks and bridges with bright lights can be very effective. And I also like targeting the same zones that were effective during the twilight periods because they’ll often hang in those same areas to feed throughout the night.

### Rigging and fishing cut mullet

-   Scent will disperse into water and attract fish

-   Put circle hook through meat in narrow end of half mullet (where tail is cut off)
-   Take it out via the skin, and remove scale that may be on the hook tip
-   Keep line slack so fish will hook itself
  -   don't try to set hook use circle hook
-   Lower drag so that if fish grabs and runs it doesn't rip mullet out of its mouth
-   tap of small pinfish is a good sign as it will attract other fish

### Cold weather fishing

-   When its cold with mud 1oz or 3oz jig, low and slow on the bottom, dredge 3in shad (texas croaker). 
-   no bouncing. 
-   fish less likely to eat when its cold so cover more ground.
-   Negative tides happen more often in the winter. These drop the water more than normal so that the fish are more concentrated in the deep pockets/channels. Find these...!
