---
title: "tackle"
---

## Set-ups

Topwater gear - 7ft medium heavy fast action spinning rod with 20lb
briad and 40lb leader

## Knots

FG knot for line to line

merl chandler canoe man knot for terminal

dirty water used the blue crab scent

## rod and reel

7'6" Rod 2500-3500 Reel

## line

15 pound line (seaguar smackdown stealth grey), 20 pound leader
(thinner=better seaguar gold label)
Mono has better abrasian resistance than flouro and is cheaper

### hooks for live bait

attach hook to leader with [orvis knot](https://www.saltstrong.com/articles/orvis-knot/)

Hook Size to Bait Size:

-   Size 2 – Under 3-inch shrimp or baitfish
-   Size 1 – I skip this size
-   Size 1/0 – 3 to 4-inch shrimp or 3-inch baitfish
-   Size 2/0 – I skip this size
-   Size 3/0 – 4+ inch shrimp or 4 to 5-inch baitfish
-   Size 4/0 –I skip this size
-   Size 5/0 – 5 to 8-inch baitfish

split shot about 1ft above hook
hook between eye and brain, under horn

Do a circle with circle hook and it will pop out

### Kayak

-   Need to have life jacket somewhere on kayak (but don't need to wear it)
-   Whistle is required
-   If fishing low light light is required - could just be head lamp